import type { Issue } from '$lib/types/issue';

export const DEMO_ISSUES: Issue[] = [
  {
    id: 'bd-epic01',
    title: 'User Authentication System',
    body: 'Implement complete authentication flow including login, logout, and session management.',
    status: 'in_progress',
    priority: 1,
    issue_type: 'epic',
    created_at: '2026-01-01T10:00:00Z',
    updated_at: '2026-01-03T14:00:00Z',
    created_by: 'kevin',
    created_by_type: 'human',
    labels: ['auth', 'security'],
    depends_on: [],
    comments: [],
  },
  {
    id: 'bd-feat01',
    title: 'Implement JWT token generation',
    body: 'Generate and validate JWT tokens for user sessions.',
    status: 'closed',
    priority: 1,
    issue_type: 'feature',
    created_at: '2026-01-01T11:00:00Z',
    updated_at: '2026-01-02T16:00:00Z',
    closed_at: '2026-01-02T16:00:00Z',
    created_by: 'kevin',
    created_by_type: 'human',
    parent_id: 'bd-epic01',
    labels: ['auth'],
    depends_on: [],
    comments: [],
  },
  {
    id: 'bd-feat02',
    title: 'Create login form UI',
    body: 'Design and implement the login form component.',
    status: 'in_progress',
    priority: 2,
    issue_type: 'feature',
    created_at: '2026-01-01T12:00:00Z',
    updated_at: '2026-01-03T10:00:00Z',
    created_by: 'kevin',
    created_by_type: 'human',
    parent_id: 'bd-epic01',
    labels: ['ui', 'auth'],
    depends_on: [{ id: 'bd-feat01', dep_type: 'blocks' }],
    comments: [],
  },
  {
    id: 'bd-task01',
    title: 'Add password validation',
    body: 'Implement client-side password strength validation.',
    status: 'open',
    priority: 2,
    issue_type: 'task',
    created_at: '2026-01-02T09:00:00Z',
    updated_at: '2026-01-02T09:00:00Z',
    created_by: 'kevin',
    created_by_type: 'human',
    parent_id: 'bd-epic01',
    labels: ['validation'],
    depends_on: [{ id: 'bd-feat02', dep_type: 'blocks' }],
    comments: [],
  },
  {
    id: 'bd-bug01',
    title: 'Fix session timeout handling',
    body: 'Sessions are not properly cleared when they expire.',
    status: 'blocked',
    priority: 1,
    issue_type: 'bug',
    created_at: '2026-01-02T14:00:00Z',
    updated_at: '2026-01-03T08:00:00Z',
    created_by: 'agent-claude',
    created_by_type: 'agent',
    agent_id: 'claude-code',
    parent_id: 'bd-epic01',
    labels: ['bug', 'auth'],
    depends_on: [{ id: 'bd-feat01', dep_type: 'blocks' }],
    comments: [
      {
        id: 'cmt-001',
        body: 'Investigating the root cause. Appears to be a race condition.',
        created_at: '2026-01-03T08:00:00Z',
        created_by: 'agent-claude',
        created_by_type: 'agent',
      },
    ],
  },
  {
    id: 'bd-epic02',
    title: 'Dashboard Redesign',
    body: 'Complete overhaul of the main dashboard UI.',
    status: 'open',
    priority: 2,
    issue_type: 'epic',
    created_at: '2026-01-02T10:00:00Z',
    updated_at: '2026-01-02T10:00:00Z',
    created_by: 'kevin',
    created_by_type: 'human',
    labels: ['ui', 'design'],
    depends_on: [{ id: 'bd-epic01', dep_type: 'waits_for' }],
    comments: [],
  },
  {
    id: 'bd-feat03',
    title: 'Create dashboard wireframes',
    body: 'Design initial wireframes for the new dashboard layout.',
    status: 'open',
    priority: 3,
    issue_type: 'feature',
    created_at: '2026-01-02T11:00:00Z',
    updated_at: '2026-01-02T11:00:00Z',
    created_by: 'kevin',
    created_by_type: 'human',
    parent_id: 'bd-epic02',
    labels: ['design'],
    depends_on: [],
    comments: [],
  },
  {
    id: 'bd-feat04',
    title: 'Implement responsive grid layout',
    body: 'Create a responsive grid system for dashboard widgets.',
    status: 'open',
    priority: 2,
    issue_type: 'feature',
    created_at: '2026-01-02T12:00:00Z',
    updated_at: '2026-01-02T12:00:00Z',
    created_by: 'kevin',
    created_by_type: 'human',
    parent_id: 'bd-epic02',
    labels: ['ui'],
    depends_on: [{ id: 'bd-feat03', dep_type: 'blocks' }],
    comments: [],
  },
  {
    id: 'bd-chore1',
    title: 'Update dependencies',
    body: 'Upgrade all npm packages to latest versions.',
    status: 'open',
    priority: 4,
    issue_type: 'chore',
    created_at: '2026-01-03T09:00:00Z',
    updated_at: '2026-01-03T09:00:00Z',
    created_by: 'kevin',
    created_by_type: 'human',
    labels: ['maintenance'],
    depends_on: [],
    comments: [],
  },
  {
    id: 'bd-task02',
    title: 'Write authentication tests',
    body: 'Add unit and integration tests for auth module.',
    status: 'open',
    priority: 2,
    issue_type: 'task',
    created_at: '2026-01-03T10:00:00Z',
    updated_at: '2026-01-03T10:00:00Z',
    created_by: 'kevin',
    created_by_type: 'human',
    parent_id: 'bd-epic01',
    labels: ['testing'],
    depends_on: [
      { id: 'bd-feat01', dep_type: 'blocks' },
      { id: 'bd-feat02', dep_type: 'blocks' },
    ],
    comments: [],
  },
];
